---
- name: ensure additional packages are installed
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libgnome-keyring-dev
    - curl
    - wget
    - xsltproc
    - libxml2-utils
    - xml-twig-tools
  sudo: yes
